/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiuUMS;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import uiuClasses.SMSclass;
import uiuClasses.Student;
/**
 *
 * @author MeRiDa
 */
public class AdminCreateStudent extends javax.swing.JFrame {

    Connection cnn;
    ResultSet res;
    PreparedStatement pst;
    
    ArrayList <Student> s = new ArrayList<> ();
    /**
     * Creates new form AdminCreateStudent
     */
    public AdminCreateStudent() {
        super("Create New Student Profile");
        initComponents();
        cnn = DBconnection.Connecrdb();
        setLocationRelativeTo(null);
        super.setResizable(false);
        addItem();
        txtPassword.setText("1234");
        txtPassword.setEditable(false);
    }
    
    private int checkUser(){
        try{
        String username = txtUsername.getText();
                String sql = "select * from StudentList where Username='"+username+"'";
                pst = cnn.prepareStatement(sql);
                res = pst.executeQuery();
                if(res.next()){
                    JOptionPane.showMessageDialog(null, "Username already existed.", null, JOptionPane.ERROR_MESSAGE);
                    txtUsername.setText("");
                    return 1;
                }
                pst.close();
                res.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return 0;
    }
    
    private int MobileValidation(String number){
        Pattern pattern = Pattern.compile("\\d{11}");
        Matcher matcher = pattern.matcher(number);
        
        if(matcher.matches()){
            return 1;
        }
        else
            return 0;
    }
    
    private void InsertDatabase(){
        try{
            String sql = "Insert into StudentList (Name,FatherName,MotherName,Address,Mobile,Email,DOB,BloodGroup,Department, Batch, CompletedTrimester, CompletedCredit, CGPA, Username, Password, GPAsum) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                pst = cnn.prepareStatement(sql);
                pst.setString(1, s.get(0).getName());
                pst.setString(2, txtFatherName.getText());
                pst.setString(3, txtMotherName.getText());
                pst.setString(4, s.get(0).getAddress());
                pst.setString(5, s.get(0).getMobile());
                pst.setString(6, s.get(0).getEmail());
                pst.setString(7, s.get(0).getDOB());
                pst.setString(8, s.get(0).getBloodGroup());
                pst.setString(9, s.get(0).getDepartment());
                pst.setString(10, s.get(0).getBatch());
                pst.setString(11, jComboBox4.getSelectedItem().toString());
                pst.setString(12, txtCompletedCredit.getText());
                pst.setString(13, txtCGPA.getText());
                pst.setString(14, s.get(0).getUsername());
                pst.setString(15, s.get(0).getPassword());
                pst.setString(16, "0");

                pst.execute();
                pst.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void addItem(){
        try{
            String sql = "select * from TrimesterList";
            pst = cnn.prepareStatement(sql);
            res = pst.executeQuery();
            while(res.next()){
                String batch = res.getString(1);
                jComboBox3.addItem(batch);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCGPA = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblBatch = new javax.swing.JLabel();
        lblCompletedTrimester = new javax.swing.JLabel();
        txtCompletedCredit = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblBloodGroup = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblMotherName = new javax.swing.JLabel();
        btnCreateProfile = new javax.swing.JButton();
        txtFatherName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblFatherName = new javax.swing.JLabel();
        lblCompletedCredit = new javax.swing.JLabel();
        lblCGPA = new javax.swing.JLabel();
        txtMotherName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtPassword = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 4));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 2), "Create Student Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 153))); // NOI18N

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPassword.setText("Password");

        lblBatch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBatch.setText("Batch");

        lblCompletedTrimester.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCompletedTrimester.setText("Completed Trimester");

        txtCompletedCredit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCompletedCreditKeyTyped(evt);
            }
        });

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddress.setText("Address");

        lblDepartment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDepartment.setText("Department");

        lblDOB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDOB.setText("Date of Birth");

        lblBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBloodGroup.setText("Blood Group");

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setText("Username");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblName.setText("Name");

        lblMobile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMobile.setText("Mobile No.");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail.setText("Email");

        lblMotherName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMotherName.setText("Mother's Name");

        btnCreateProfile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCreateProfile.setText("Create Profile");
        btnCreateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateProfileActionPerformed(evt);
            }
        });

        lblFatherName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFatherName.setText("Father's Name");

        lblCompletedCredit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCompletedCredit.setText("Completed Credit");

        lblCGPA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCGPA.setText("CGPA");

        txtMotherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotherNameActionPerformed(evt);
            }
        });

        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMobileKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileKeyTyped(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<None>", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<None>", "CSE", "EEE" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<None>" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<None>", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblUsername)
                            .addComponent(lblCGPA)
                            .addComponent(lblCompletedCredit)
                            .addComponent(lblCompletedTrimester)
                            .addComponent(lblBatch)
                            .addComponent(lblDepartment)
                            .addComponent(lblBloodGroup)
                            .addComponent(lblDOB)
                            .addComponent(lblEmail)
                            .addComponent(lblMobile)
                            .addComponent(lblAddress)
                            .addComponent(lblMotherName)
                            .addComponent(lblFatherName)
                            .addComponent(lblName))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAddress)
                            .addComponent(txtMobile)
                            .addComponent(txtEmail)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(txtCompletedCredit)
                            .addComponent(txtCGPA)
                            .addComponent(txtUsername)
                            .addComponent(txtPassword)
                            .addComponent(txtFatherName)
                            .addComponent(txtMotherName)
                            .addComponent(txtName)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateProfile)))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFatherName)
                    .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMotherName)
                    .addComponent(txtMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobile)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodGroup)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBatch)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompletedTrimester)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCompletedCredit)
                    .addComponent(txtCompletedCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCGPA)
                    .addComponent(txtCGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateProfile)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtMotherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotherNameActionPerformed

    private void btnCreateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateProfileActionPerformed
        // TODO add your handling code here:
        try{
            int checkExistedUsername = checkUser();
            String d1 = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
            if(txtName.getText().isEmpty() || txtFatherName.getText().isEmpty() || txtMotherName.getText().isEmpty() || txtAddress.getText().isEmpty() || txtMobile.getText().isEmpty() || txtEmail.getText().isEmpty() || d1.equals("") || jComboBox1.getSelectedIndex()==0 || jComboBox2.getSelectedIndex()==0 || jComboBox3.getSelectedIndex()==0 || jComboBox4.getSelectedIndex()==0 || txtCompletedCredit.getText().isEmpty() || txtCGPA.getText().isEmpty() || txtUsername.getText().isEmpty() || txtPassword.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please fill required fields.", null, JOptionPane.ERROR_MESSAGE);
            }
            else{
                String a1 = txtName.getText();
                String a6 = txtAddress.getText();
                String a4 = txtMobile.getText();
                String a5 = txtEmail.getText();
                String a7 = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
                String a8 = jComboBox1.getSelectedItem().toString();
                String a9 = jComboBox2.getSelectedItem().toString();
                String a10 = jComboBox3.getSelectedItem().toString();
                String a2 = txtUsername.getText();
                String a3 = txtPassword.getText();
                
                int mobileValidation = MobileValidation(txtMobile.getText());
                //Email Validation
                if(!Pattern.matches("^[0-9a-zA-Z\\.]+[@]{1}+[0-9a-zA-Z\\.]+[.]{1}+[0-9a-zA-Z\\.]+$", txtEmail.getText())){
                JOptionPane.showMessageDialog(null, "Please enter a valid email", "Invalid Email Address", JOptionPane.ERROR_MESSAGE);
                txtEmail.setText("");
                }
                else if(mobileValidation == 0){
                    JOptionPane.showMessageDialog(null, "Please enter a valid number", "Invalid Mobile Number", JOptionPane.ERROR_MESSAGE);
                    txtMobile.setText("");
                }
                
                else if(checkExistedUsername == 0){
                pst.close();
                res.close();
                if(checkExistedUsername==0){
                    s.add(new Student(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10));
                    InsertDatabase();
                    JOptionPane.showMessageDialog(null, "New Student Profile Created!");
                    txtName.setText("");
                    txtFatherName.setText("");
                    txtMotherName.setText("");
                    txtAddress.setText("");
                    txtMobile.setText("");
                    txtEmail.setText("");
                    jDateChooser1.setCalendar(null);
                    jComboBox1.setSelectedIndex(0);
                    jComboBox2.setSelectedIndex(0);
                    jComboBox3.setSelectedIndex(0);
                    jComboBox4.setSelectedIndex(0);
                    txtCompletedCredit.setText("");
                    txtCGPA.setText("");
                    txtUsername.setText("");
                    
                    //send sms
                    String name = a1;
                    String num = a4;
                    String username = a2;
                    String password = txtPassword.getText();
                    
                    String[] word = name.split(" ");
                    name = word[(word.length)-1];
                    String number = "+88" + num;
                    SMSclass.sms(name, number, username, password);
                    }
                }
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_btnCreateProfileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        AdminHome ah = new AdminHome();
        ah.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtMobileKeyPressed

    private void txtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUsernameKeyPressed

    private void txtMobileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)
            evt.consume();
    }//GEN-LAST:event_txtMobileKeyTyped

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)
            evt.consume();
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void txtCompletedCreditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompletedCreditKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)
            evt.consume();
    }//GEN-LAST:event_txtCompletedCreditKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AdminCreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AdminCreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AdminCreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AdminCreateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AdminCreateStudent().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateProfile;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBatch;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblCGPA;
    private javax.swing.JLabel lblCompletedCredit;
    private javax.swing.JLabel lblCompletedTrimester;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFatherName;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblMotherName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCGPA;
    private javax.swing.JTextField txtCompletedCredit;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtMotherName;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
