/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiuUMS;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author MeRiDa
 */
public class StudentProfile extends javax.swing.JFrame {

    Connection cnn;
    ResultSet res;
    PreparedStatement pst;
    /**
     * Creates new form StudentProfile
     */
    public StudentProfile() {
        super("Personal Information");
        initComponents();
        cnn = DBconnection.Connecrdb();
        setLocationRelativeTo(null);
        Profile();
        super.setResizable(false);
    }
    
    private void Profile(){
        try{
            int id = 1;
            String sql2 = "select * from ExtraInfo where row='"+id+"'";
            pst = cnn.prepareStatement(sql2);
            res = pst.executeQuery();
            String currentUser = res.getString(2);
            res.close();
            pst.close();
            String sql = "select * from StudentList where Username = '"+currentUser+"'";
            pst = cnn.prepareStatement(sql);
            res = pst.executeQuery();
            if(res.next())
            {
                String add1 = res.getString("Name");
                lblshowName.setText(add1);
                String add2 = res.getString("FatherName");
                lblshowFatherName.setText(add2);
                String add3 = res.getString("MotherName");
                lblshowMotherName.setText(add3);
                String add4 = res.getString("Address");
                lblshowAddress.setText(add4);
                String add5 = res.getString("Mobile");
                lblshowMobile.setText(add5);
                String add6 = res.getString("Email");
                lblshowEmail.setText(add6);
                String add7 = res.getString("DOB");
                lblshowDOB.setText(add7);
                String add8 = res.getString("BloodGroup");
                lblshowBloodGroup.setText(add8);
                res.close();
                pst.close();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try{
                res.close();
                pst.close();
            }
            catch(Exception e)
            {
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblshowEmail = new javax.swing.JLabel();
        lblshowMobile = new javax.swing.JLabel();
        lblshowDOB = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        lblFatherName = new javax.swing.JLabel();
        lblMotherName = new javax.swing.JLabel();
        lblshowAddress = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblshowMotherName = new javax.swing.JLabel();
        lblshowBloodGroup = new javax.swing.JLabel();
        lblshowFatherName = new javax.swing.JLabel();
        lblBloodGroup = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblshowName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 4));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 153), 2), "Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 102, 153))); // NOI18N

        lblshowEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblshowEmail.setText("jLabel2");

        lblshowMobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblshowMobile.setText("jLabel2");

        lblshowDOB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblshowDOB.setText("jLabel2");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEmail.setText("Email");

        lblMobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMobile.setText("Mobile No.");

        lblFatherName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblFatherName.setText("Father's Name");

        lblMotherName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMotherName.setText("Mother's Name");

        lblshowAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblshowAddress.setText("jLabel2");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("Name");

        lblDOB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDOB.setText("Date of Birth");

        lblshowMotherName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblshowMotherName.setText("jLabel2");

        lblshowBloodGroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblshowBloodGroup.setText("jLabel2");

        lblshowFatherName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblshowFatherName.setText("jLabel2");

        lblBloodGroup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBloodGroup.setText("Blood Group");

        lblAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddress.setText("Address");

        lblshowName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblshowName.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblBloodGroup)
                    .addComponent(lblDOB)
                    .addComponent(lblEmail)
                    .addComponent(lblMobile)
                    .addComponent(lblAddress)
                    .addComponent(lblMotherName)
                    .addComponent(lblFatherName))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblshowDOB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblshowEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblshowMobile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblshowAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblshowMotherName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblshowFatherName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(lblshowName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblshowBloodGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addGap(18, 18, 18)
                        .addComponent(lblFatherName)
                        .addGap(18, 18, 18)
                        .addComponent(lblMotherName)
                        .addGap(18, 18, 18)
                        .addComponent(lblAddress)
                        .addGap(18, 18, 18)
                        .addComponent(lblMobile)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmail)
                        .addGap(18, 18, 18)
                        .addComponent(lblDOB)
                        .addGap(18, 18, 18)
                        .addComponent(lblBloodGroup))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblshowName)
                        .addGap(18, 18, 18)
                        .addComponent(lblshowFatherName)
                        .addGap(18, 18, 18)
                        .addComponent(lblshowMotherName)
                        .addGap(18, 18, 18)
                        .addComponent(lblshowAddress)
                        .addGap(18, 18, 18)
                        .addComponent(lblshowMobile)
                        .addGap(18, 18, 18)
                        .addComponent(lblshowEmail)
                        .addGap(18, 18, 18)
                        .addComponent(lblshowDOB)
                        .addGap(18, 18, 18)
                        .addComponent(lblshowBloodGroup)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        StudentHome sh = new StudentHome();
        sh.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentProfile().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBloodGroup;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFatherName;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblMotherName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblshowAddress;
    private javax.swing.JLabel lblshowBloodGroup;
    private javax.swing.JLabel lblshowDOB;
    private javax.swing.JLabel lblshowEmail;
    private javax.swing.JLabel lblshowFatherName;
    private javax.swing.JLabel lblshowMobile;
    private javax.swing.JLabel lblshowMotherName;
    private javax.swing.JLabel lblshowName;
    // End of variables declaration//GEN-END:variables
}
